version: '2.1'
services:
  hello-service-1:
    environment:
      - service_name="Service Instance A"
    build:
      service/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/hello"]
      interval: 10s
      timeout: 10s
      retries: 3
  hello-service-2:
    environment:
        - service_name="Service Instance B"
    build:
      service/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/hello"]
      interval: 10s
      timeout: 10s
      retries: 3
  hello-service-load-balancer:
    build:
      loadbalancer/
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      hello-service-1:
        condition: service_healthy
      hello-service-2:
        condition: service_healthy